### ISSUE TITLE
magento not on the list

### ISSUE THREAD

**Issue by LucaPizzagalli** [netlify/headlesscms.org#131]
Hello,
Why isn't magento https://github.com/magento/magento2 not in the list? Is it just missing or it dosen't satisfy some criteria?

**Comment by DirtyF** [comment]
Because Magento is not a headless CMS :)
https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

**Comment by LucaPizzagalli** [comment]
Ops :)
Thank you for the answer.
I'll just go a litte OT before closing the issue. Can a CMS like Bloomreach Experience Manager that clames to have headless features ( https://www.bloomreach.com/en/products/bloomreach-experience/headless-cms ) be considered headless or is more a marketing proposition?

**Comment by erquhart** [comment]
Bloomreach does appear to be able to function headless, so I suppose so.
