### ISSUE TITLE
Incorrectly sorting Github stars (7 days)

### ISSUE THREAD

**Issue by roborich** [netlify/headlesscms.org#133]
With the sorting set to `GitHub Stars (7 days)` a presumably brand new headless CMS is in the number 1 spot with only 5 stars total, 5 new stars.  At first, I was excited to see a new top dog CMS, only to find out it's a completely unused CMS.

See attached screenshot.

![Screenshot from 2019-06-11 11-14-36](https://user-images.githubusercontent.com/4225069/59284487-54c99680-8c3a-11e9-9851-a9b744480337.png)

**Comment by erquhart** [comment]
Good catch, thanks for the heads up - rolled back to the last accurate version until we figure out what happened.
