### ISSUE TITLE
Shouldn't Wordpress be added?

### ISSUE THREAD

**Issue by ad-si** [netlify/headlesscms.org#203]
As far as I understand, It has a proper REST API and can therefore be used as a headless CMS: https://developer.wordpress.org/rest-api/

Others seem to agree: https://fettblog.eu/wordpress-and-jamstack-sites/

Don't you think?

**Comment by erquhart** [comment]
Wordpress still doesn't "just work" for headless, that's the issue. It's possible, but rough.

Here's a recent talk on the subject: https://www.youtube.com/watch?v=g0OfnWCcBk4

**Comment by philhawksworth** [comment]
Perhaps we can add this when there is a very clear and direct positioning of WordPress as a headless CMS. For the moment, I'm closing this.
