### ISSUE TITLE
still needed..

### ISSUE THREAD

**Issue by ChrBach** [netlify/headlesscms.org#6]
- [x] The About copy hasn't been updated?
- [x] It still says “application:” on all of them, that needs removing,

- [ ]  (T as short for JAMstack doesn't work, we can't use it like that).

- [x] The contact page just have everything in one sentence. It should break when it concerns the formula.

- [x] Error: This is actually written out on the contact page: Check [The Rules](“/rules”) 

- [x] The favicon looks weird (Should have it's own I guess).

- [x] Share button should open reddit and HN icons as well

- [x] Cloud CMS support site generators is empty. It should say All.

- [x] In general it seems like the copy is off for the Contact page. Did you remember to paste it in?

**Comment by calavera** [comment]
closing this as the last remaining item in the list doesn't apply anymore.
