### ISSUE TITLE
Laravel Voyager

### ISSUE THREAD

**Issue by johnss** [netlify/headlesscms.org#99]
Is laravel voyager can be considered headless cms?
It is like a CMS but admin panel only (front end less),
if yes please add to the list!
http://laravelvoyager.com
http://github.com/the-control-group/voyager

**Comment by erquhart** [comment]
From [their docs](https://voyager.readme.io/docs/what-is-voyager):

<img width="352" alt="screen shot 2018-08-21 at 9 13 09 pm" src="https://user-images.githubusercontent.com/2112202/44437222-11a51680-a587-11e8-8c9f-2db0c04de3a0.png">

Perhaps more helpful:

> Voyager is not a CMS or a blogging platform. But it can be used to create a CMS or a blogging platform, but out of the box it is neither of those.

It's also not headless, it lives on the server with your Laravel app, but sounds like you could use it to create a headless CMS.

**Comment by johnss** [comment]
Although they claim its not a cms, it actually an admin panel only CMS, for example if you want to create a menu you can create it from the GUI, you can create new table which can be equivalent to wordpress custom post type.

Interface is similar to phpMyAdmin, for example you want to create list of "dogs", you can create table called "dogs", which can be equivalent to wordpress custom post type "dogs", please read it here
https://www.sitepoint.com/voyager-can-an-admin-interface-make-laravel-even-more-approachable/

on the front end its blank, it leave up to the users to decide to go headless or not, its possible to create headless cms by creating a rest api

**Comment by erquhart** [comment]
I'd say if someone used this to create a headless CMS that'd be awesome. As it stands it's more of a framework with the potential to drive a Headless CMS.
